inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - bin/**
    - vendor/bundle/**/*

# Per team developer playbook
RSpec/MultipleMemoizedHelpers:
  Enabled: false

# Layout
Layout/LineLength:
  Max: 150

# Naming
Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - have_
