#!/bin/bash --login

# This script is called by our weekly dependency update job in Jenkins after updating Ruby and other deps

# Switch to Ruby 3.1 for GlobusClient (3.0 is default in Jenkinsfile)
rvm use 3.1.2@globus_client --create &&
    gem install bundler &&
    bundle install --gemfile Gemfile

standardrb --fix > globus_client_standard.txt

retVal=$?

git commit -am "Update to latest standard style guide"

if [ $retVal -ne 0 ]; then
    echo "ERROR UPDATING RUBY TO STANDARD STYLE (globus_client)"
    cat globus_client_standard.txt
fi
